<script src="vendor/jquery/jquery.min.js"></script>
<script src="js/user/jquery-migrate-3.0.1.min.js"></script>
<script src="js/user/popper.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="js/user/jquery.easing.1.3.js"></script>
<script src="js/user/jquery.waypoints.min.js"></script>
<script src="js/user/jquery.stellar.min.js"></script>
<script src="js/user/owl.carousel.min.js"></script>
<script src="js/user/jquery.magnific-popup.min.js"></script>
<script src="js/user/aos.js"></script>
<script src="js/user/jquery.animateNumber.min.js"></script>
<script src="js/user/bootstrap-datepicker.js"></script>
<script src="js/user/scrollax.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="js/user/google-map.js"></script>
<script src="js/user/main.js"></script>
